// AUTO-GENERATED from OpenFontIcons.ttx
#pragma once

// Private-Use icons U+E000–U+F8FF
#define ICON_MIN_FA "\uE000"   // Icon start range
#define ICON_MAX_FA "\uF8FF"   // Icon end range

#define ICON_ACTIVITY "\uE000"   // activity
#define ICON_AIRPLAY "\uE001"   // airplay
#define ICON_ALERT_CIRCLE "\uE002"   // alert-circle
#define ICON_ALERT_OCTAGON "\uE003"   // alert-octagon
#define ICON_ALERT_TRIANGLE "\uE004"   // alert-triangle
#define ICON_ALIGN_CENTER "\uE005"   // align-center
#define ICON_ALIGN_JUSTIFY "\uE006"   // align-justify
#define ICON_ALIGN_LEFT "\uE007"   // align-left
#define ICON_ALIGN_RIGHT "\uE008"   // align-right
#define ICON_ANCHOR "\uE009"   // anchor
#define ICON_APERTURE "\uE00A"   // aperture
#define ICON_ARCHIVE "\uE00B"   // archive
#define ICON_ARROW_DOWN_CIRCLE "\uE00C"   // arrow-down-circle
#define ICON_ARROW_DOWN_LEFT "\uE00D"   // arrow-down-left
#define ICON_ARROW_DOWN_RIGHT "\uE00E"   // arrow-down-right
#define ICON_ARROW_DOWN "\uE00F"   // arrow-down
#define ICON_ARROW_LEFT_CIRCLE "\uE010"   // arrow-left-circle
#define ICON_ARROW_LEFT "\uE011"   // arrow-left
#define ICON_ARROW_RIGHT_CIRCLE "\uE012"   // arrow-right-circle
#define ICON_ARROW_RIGHT "\uE013"   // arrow-right
#define ICON_ARROW_UP_CIRCLE "\uE014"   // arrow-up-circle
#define ICON_ARROW_UP_LEFT "\uE015"   // arrow-up-left
#define ICON_ARROW_UP_RIGHT "\uE016"   // arrow-up-right
#define ICON_ARROW_UP "\uE017"   // arrow-up
#define ICON_AT_SIGN "\uE018"   // at-sign
#define ICON_AWARD "\uE019"   // award
#define ICON_BAR_CHART_2 "\uE01A"   // bar-chart-2
#define ICON_BAR_CHART "\uE01B"   // bar-chart
#define ICON_BATTERY_CHARGING "\uE01C"   // battery-charging
#define ICON_BATTERY "\uE01D"   // battery
#define ICON_BELL_OFF "\uE01E"   // bell-off
#define ICON_BELL "\uE01F"   // bell
#define ICON_BLUETOOTH "\uE020"   // bluetooth
#define ICON_BOLD "\uE021"   // bold
#define ICON_BOOK_OPEN "\uE022"   // book-open
#define ICON_BOOK "\uE023"   // book
#define ICON_BOOKMARK "\uE024"   // bookmark
#define ICON_BOX "\uE025"   // box
#define ICON_BRIEFCASE "\uE026"   // briefcase
#define ICON_CALENDAR "\uE027"   // calendar
#define ICON_CAMERA_OFF "\uE028"   // camera-off
#define ICON_CAMERA "\uE029"   // camera
#define ICON_CAST "\uE02A"   // cast
#define ICON_CHECK_CIRCLE "\uE02B"   // check-circle
#define ICON_CHECK_SQUARE "\uE02C"   // check-square
#define ICON_CHECK "\uE02D"   // check
#define ICON_CHEVRON_DOWN "\uE02E"   // chevron-down
#define ICON_CHEVRON_LEFT "\uE02F"   // chevron-left
#define ICON_CHEVRON_RIGHT "\uE030"   // chevron-right
#define ICON_CHEVRON_UP "\uE031"   // chevron-up
#define ICON_CHEVRONS_DOWN "\uE032"   // chevrons-down
#define ICON_CHEVRONS_LEFT "\uE033"   // chevrons-left
#define ICON_CHEVRONS_RIGHT "\uE034"   // chevrons-right
#define ICON_CHEVRONS_UP "\uE035"   // chevrons-up
#define ICON_CIRCLE "\uE036"   // circle
#define ICON_CLIPBOARD "\uE037"   // clipboard
#define ICON_CLOCK "\uE038"   // clock
#define ICON_CLOUD_DRIZZLE "\uE039"   // cloud-drizzle
#define ICON_CLOUD_LIGHTNING "\uE03A"   // cloud-lightning
#define ICON_CLOUD_OFF "\uE03B"   // cloud-off
#define ICON_CLOUD_RAIN "\uE03C"   // cloud-rain
#define ICON_CLOUD_SNOW "\uE03D"   // cloud-snow
#define ICON_CLOUD "\uE03E"   // cloud
#define ICON_CODE "\uE03F"   // code
#define ICON_COMMAND "\uE040"   // command
#define ICON_COMPASS "\uE041"   // compass
#define ICON_COPY "\uE042"   // copy
#define ICON_CORNER_DOWN_LEFT "\uE043"   // corner-down-left
#define ICON_CORNER_DOWN_RIGHT "\uE044"   // corner-down-right
#define ICON_CORNER_LEFT_DOWN "\uE045"   // corner-left-down
#define ICON_CORNER_LEFT_UP "\uE046"   // corner-left-up
#define ICON_CORNER_RIGHT_DOWN "\uE047"   // corner-right-down
#define ICON_CORNER_RIGHT_UP "\uE048"   // corner-right-up
#define ICON_CORNER_UP_LEFT "\uE049"   // corner-up-left
#define ICON_CORNER_UP_RIGHT "\uE04A"   // corner-up-right
#define ICON_CPU "\uE04B"   // cpu
#define ICON_CREDIT_CARD "\uE04C"   // credit-card
#define ICON_CROP "\uE04D"   // crop
#define ICON_CROSSHAIR "\uE04E"   // crosshair
#define ICON_DATABASE "\uE04F"   // database
#define ICON_DELETE "\uE050"   // delete
#define ICON_DISC "\uE051"   // disc
#define ICON_DOLLAR_SIGN "\uE052"   // dollar-sign
#define ICON_DOWNLOAD_CLOUD "\uE053"   // download-cloud
#define ICON_DOWNLOAD "\uE054"   // download
#define ICON_DROPLET "\uE055"   // droplet
#define ICON_EDIT_2 "\uE056"   // edit-2
#define ICON_EDIT_3 "\uE057"   // edit-3
#define ICON_EDIT "\uE058"   // edit
#define ICON_EXTERNAL_LINK "\uE059"   // external-link
#define ICON_EYE_OFF "\uE05A"   // eye-off
#define ICON_EYE "\uE05B"   // eye
#define ICON_FAST_FORWARD "\uE05C"   // fast-forward
#define ICON_FEATHER "\uE05D"   // feather
#define ICON_FILE_MINUS "\uE05E"   // file-minus
#define ICON_FILE_PLUS "\uE05F"   // file-plus
#define ICON_FILE_TEXT "\uE060"   // file-text
#define ICON_FILE "\uE061"   // file
#define ICON_FILM "\uE062"   // film
#define ICON_FILTER "\uE063"   // filter
#define ICON_FLAG "\uE064"   // flag
#define ICON_FOLDER_MINUS "\uE065"   // folder-minus
#define ICON_FOLDER_PLUS "\uE066"   // folder-plus
#define ICON_FOLDER "\uE067"   // folder
#define ICON_GIFT "\uE068"   // gift
#define ICON_GIT_BRANCH "\uE069"   // git-branch
#define ICON_GIT_COMMIT "\uE06A"   // git-commit
#define ICON_GIT_MERGE "\uE06B"   // git-merge
#define ICON_GIT_PULL_REQUEST "\uE06C"   // git-pull-request
#define ICON_GLOBE "\uE06D"   // globe
#define ICON_GRID "\uE06E"   // grid
#define ICON_HARD_DRIVE "\uE06F"   // hard-drive
#define ICON_HASH "\uE070"   // hash
#define ICON_HEADPHONES "\uE071"   // headphones
#define ICON_HEART "\uE072"   // heart
#define ICON_HELP_CIRCLE "\uE073"   // help-circle
#define ICON_HOME "\uE074"   // home
#define ICON_IMAGE "\uE075"   // image
#define ICON_INBOX "\uE076"   // inbox
#define ICON_INFO "\uE077"   // info
#define ICON_ITALIC "\uE078"   // italic
#define ICON_LAYERS "\uE079"   // layers
#define ICON_LAYOUT "\uE07A"   // layout
#define ICON_LIFE_BUOY "\uE07B"   // life-buoy
#define ICON_LINK_2 "\uE07C"   // link-2
#define ICON_LINK "\uE07D"   // link
#define ICON_LIST "\uE07E"   // list
#define ICON_LOADER "\uE07F"   // loader
#define ICON_LOCK "\uE080"   // lock
#define ICON_LOG_IN "\uE081"   // log-in
#define ICON_LOG_OUT "\uE082"   // log-out
#define ICON_MAIL "\uE083"   // mail
#define ICON_MAP_PIN "\uE084"   // map-pin
#define ICON_MAP "\uE085"   // map
#define ICON_MAXIMIZE_2 "\uE086"   // maximize-2
#define ICON_MAXIMIZE "\uE087"   // maximize
#define ICON_MENU "\uE088"   // menu
#define ICON_MESSAGE_CIRCLE "\uE089"   // message-circle
#define ICON_MESSAGE_SQUARE "\uE08A"   // message-square
#define ICON_MIC_OFF "\uE08B"   // mic-off
#define ICON_MIC "\uE08C"   // mic
#define ICON_MINIMIZE_2 "\uE08D"   // minimize-2
#define ICON_MINIMIZE "\uE08E"   // minimize
#define ICON_MINUS_CIRCLE "\uE08F"   // minus-circle
#define ICON_MINUS_SQUARE "\uE090"   // minus-square
#define ICON_MINUS "\uE091"   // minus
#define ICON_MONITOR "\uE092"   // monitor
#define ICON_MOON "\uE093"   // moon
#define ICON_MORE_HORIZONTAL "\uE094"   // more-horizontal
#define ICON_MORE_VERTICAL "\uE095"   // more-vertical
#define ICON_MOVE "\uE096"   // move
#define ICON_MUSIC "\uE097"   // music
#define ICON_NAVIGATION_2 "\uE098"   // navigation-2
#define ICON_NAVIGATION "\uE099"   // navigation
#define ICON_OCTAGON "\uE09A"   // octagon
#define ICON_PACKAGE "\uE09B"   // package
#define ICON_PAPERCLIP "\uE09C"   // paperclip
#define ICON_PAUSE_CIRCLE "\uE09D"   // pause-circle
#define ICON_PAUSE "\uE09E"   // pause
#define ICON_PERCENT "\uE09F"   // percent
#define ICON_PHONE_CALL "\uE0A0"   // phone-call
#define ICON_PHONE_FORWARDED "\uE0A1"   // phone-forwarded
#define ICON_PHONE_INCOMING "\uE0A2"   // phone-incoming
#define ICON_PHONE_MISSED "\uE0A3"   // phone-missed
#define ICON_PHONE_OFF "\uE0A4"   // phone-off
#define ICON_PHONE_OUTGOING "\uE0A5"   // phone-outgoing
#define ICON_PHONE "\uE0A6"   // phone
#define ICON_PIE_CHART "\uE0A7"   // pie-chart
#define ICON_PLAY_CIRCLE "\uE0A8"   // play-circle
#define ICON_PLAY "\uE0A9"   // play
#define ICON_PLUS_CIRCLE "\uE0AA"   // plus-circle
#define ICON_PLUS_SQUARE "\uE0AB"   // plus-square
#define ICON_PLUS "\uE0AC"   // plus
#define ICON_POWER "\uE0AD"   // power
#define ICON_PRINTER "\uE0AE"   // printer
#define ICON_RADIO "\uE0AF"   // radio
#define ICON_REFRESH_CCW "\uE0B0"   // refresh-ccw
#define ICON_REFRESH_CW "\uE0B1"   // refresh-cw
#define ICON_REPEAT "\uE0B2"   // repeat
#define ICON_REWIND "\uE0B3"   // rewind
#define ICON_ROTATE_CCW "\uE0B4"   // rotate-ccw
#define ICON_ROTATE_CW "\uE0B5"   // rotate-cw
#define ICON_RSS "\uE0B6"   // rss
#define ICON_SAVE "\uE0B7"   // save
#define ICON_SCISSORS "\uE0B8"   // scissors
#define ICON_SEARCH "\uE0B9"   // search
#define ICON_SEND "\uE0BA"   // send
#define ICON_SERVER "\uE0BB"   // server
#define ICON_SETTINGS "\uE0BC"   // settings
#define ICON_SHARE_2 "\uE0BD"   // share-2
#define ICON_SHARE "\uE0BE"   // share
#define ICON_SHIELD_OFF "\uE0BF"   // shield-off
#define ICON_SHIELD "\uE0C0"   // shield
#define ICON_SHOPPING_BAG "\uE0C1"   // shopping-bag
#define ICON_SHOPPING_CART "\uE0C2"   // shopping-cart
#define ICON_SHUFFLE "\uE0C3"   // shuffle
#define ICON_SIDEBAR "\uE0C4"   // sidebar
#define ICON_SKIP_BACK "\uE0C5"   // skip-back
#define ICON_SKIP_FORWARD "\uE0C6"   // skip-forward
#define ICON_SLASH "\uE0C7"   // slash
#define ICON_SLIDERS "\uE0C8"   // sliders
#define ICON_SMARTPHONE "\uE0C9"   // smartphone
#define ICON_SPEAKER "\uE0CA"   // speaker
#define ICON_SQUARE "\uE0CB"   // square
#define ICON_STAR "\uE0CC"   // star
#define ICON_STOP_CIRCLE "\uE0CD"   // stop-circle
#define ICON_SUN "\uE0CE"   // sun
#define ICON_SUNRISE "\uE0CF"   // sunrise
#define ICON_SUNSET "\uE0D0"   // sunset
#define ICON_TABLET "\uE0D1"   // tablet
#define ICON_TAG "\uE0D2"   // tag
#define ICON_TARGET "\uE0D3"   // target
#define ICON_TERMINAL "\uE0D4"   // terminal
#define ICON_THERMOMETER "\uE0D5"   // thermometer
#define ICON_THUMBS_DOWN "\uE0D6"   // thumbs-down
#define ICON_THUMBS_UP "\uE0D7"   // thumbs-up
#define ICON_TOGGLE_LEFT "\uE0D8"   // toggle-left
#define ICON_TOGGLE_RIGHT "\uE0D9"   // toggle-right
#define ICON_TRASH_2 "\uE0DA"   // trash-2
#define ICON_TRASH "\uE0DB"   // trash
#define ICON_TRENDING_DOWN "\uE0DC"   // trending-down
#define ICON_TRENDING_UP "\uE0DD"   // trending-up
#define ICON_TRIANGLE "\uE0DE"   // triangle
#define ICON_TRUCK "\uE0DF"   // truck
#define ICON_TV "\uE0E0"   // tv
#define ICON_TYPE "\uE0E1"   // type
#define ICON_UMBRELLA "\uE0E2"   // umbrella
#define ICON_UNDERLINE "\uE0E3"   // underline
#define ICON_UNLOCK "\uE0E4"   // unlock
#define ICON_UPLOAD_CLOUD "\uE0E5"   // upload-cloud
#define ICON_UPLOAD "\uE0E6"   // upload
#define ICON_USER_CHECK "\uE0E7"   // user-check
#define ICON_USER_MINUS "\uE0E8"   // user-minus
#define ICON_USER_PLUS "\uE0E9"   // user-plus
#define ICON_USER_X "\uE0EA"   // user-x
#define ICON_USER "\uE0EB"   // user
#define ICON_USERS "\uE0EC"   // users
#define ICON_VIDEO_OFF "\uE0ED"   // video-off
#define ICON_VIDEO "\uE0EE"   // video
#define ICON_VOICEMAIL "\uE0EF"   // voicemail
#define ICON_VOLUME_1 "\uE0F0"   // volume-1
#define ICON_VOLUME_2 "\uE0F1"   // volume-2
#define ICON_VOLUME_X "\uE0F2"   // volume-x
#define ICON_VOLUME "\uE0F3"   // volume
#define ICON_WATCH "\uE0F4"   // watch
#define ICON_WIFI_OFF "\uE0F5"   // wifi-off
#define ICON_WIFI "\uE0F6"   // wifi
#define ICON_WIND "\uE0F7"   // wind
#define ICON_X_CIRCLE "\uE0F8"   // x-circle
#define ICON_X_SQUARE "\uE0F9"   // x-square
#define ICON_X "\uE0FA"   // x
#define ICON_ZAP_OFF "\uE0FB"   // zap-off
#define ICON_ZAP "\uE0FC"   // zap
#define ICON_ZOOM_IN "\uE0FD"   // zoom-in
#define ICON_ZOOM_OUT "\uE0FE"   // zoom-out
#define ICON_ACTIVITY "\uE000"   // activity
#define ICON_AIRPLAY "\uE001"   // airplay
#define ICON_ALERT_CIRCLE "\uE002"   // alert-circle
#define ICON_ALERT_OCTAGON "\uE003"   // alert-octagon
#define ICON_ALERT_TRIANGLE "\uE004"   // alert-triangle
#define ICON_ALIGN_CENTER "\uE005"   // align-center
#define ICON_ALIGN_JUSTIFY "\uE006"   // align-justify
#define ICON_ALIGN_LEFT "\uE007"   // align-left
#define ICON_ALIGN_RIGHT "\uE008"   // align-right
#define ICON_ANCHOR "\uE009"   // anchor
#define ICON_APERTURE "\uE00A"   // aperture
#define ICON_ARCHIVE "\uE00B"   // archive
#define ICON_ARROW_DOWN_CIRCLE "\uE00C"   // arrow-down-circle
#define ICON_ARROW_DOWN_LEFT "\uE00D"   // arrow-down-left
#define ICON_ARROW_DOWN_RIGHT "\uE00E"   // arrow-down-right
#define ICON_ARROW_DOWN "\uE00F"   // arrow-down
#define ICON_ARROW_LEFT_CIRCLE "\uE010"   // arrow-left-circle
#define ICON_ARROW_LEFT "\uE011"   // arrow-left
#define ICON_ARROW_RIGHT_CIRCLE "\uE012"   // arrow-right-circle
#define ICON_ARROW_RIGHT "\uE013"   // arrow-right
#define ICON_ARROW_UP_CIRCLE "\uE014"   // arrow-up-circle
#define ICON_ARROW_UP_LEFT "\uE015"   // arrow-up-left
#define ICON_ARROW_UP_RIGHT "\uE016"   // arrow-up-right
#define ICON_ARROW_UP "\uE017"   // arrow-up
#define ICON_AT_SIGN "\uE018"   // at-sign
#define ICON_AWARD "\uE019"   // award
#define ICON_BAR_CHART_2 "\uE01A"   // bar-chart-2
#define ICON_BAR_CHART "\uE01B"   // bar-chart
#define ICON_BATTERY_CHARGING "\uE01C"   // battery-charging
#define ICON_BATTERY "\uE01D"   // battery
#define ICON_BELL_OFF "\uE01E"   // bell-off
#define ICON_BELL "\uE01F"   // bell
#define ICON_BLUETOOTH "\uE020"   // bluetooth
#define ICON_BOLD "\uE021"   // bold
#define ICON_BOOK_OPEN "\uE022"   // book-open
#define ICON_BOOK "\uE023"   // book
#define ICON_BOOKMARK "\uE024"   // bookmark
#define ICON_BOX "\uE025"   // box
#define ICON_BRIEFCASE "\uE026"   // briefcase
#define ICON_CALENDAR "\uE027"   // calendar
#define ICON_CAMERA_OFF "\uE028"   // camera-off
#define ICON_CAMERA "\uE029"   // camera
#define ICON_CAST "\uE02A"   // cast
#define ICON_CHECK_CIRCLE "\uE02B"   // check-circle
#define ICON_CHECK_SQUARE "\uE02C"   // check-square
#define ICON_CHECK "\uE02D"   // check
#define ICON_CHEVRON_DOWN "\uE02E"   // chevron-down
#define ICON_CHEVRON_LEFT "\uE02F"   // chevron-left
#define ICON_CHEVRON_RIGHT "\uE030"   // chevron-right
#define ICON_CHEVRON_UP "\uE031"   // chevron-up
#define ICON_CHEVRONS_DOWN "\uE032"   // chevrons-down
#define ICON_CHEVRONS_LEFT "\uE033"   // chevrons-left
#define ICON_CHEVRONS_RIGHT "\uE034"   // chevrons-right
#define ICON_CHEVRONS_UP "\uE035"   // chevrons-up
#define ICON_CIRCLE "\uE036"   // circle
#define ICON_CLIPBOARD "\uE037"   // clipboard
#define ICON_CLOCK "\uE038"   // clock
#define ICON_CLOUD_DRIZZLE "\uE039"   // cloud-drizzle
#define ICON_CLOUD_LIGHTNING "\uE03A"   // cloud-lightning
#define ICON_CLOUD_OFF "\uE03B"   // cloud-off
#define ICON_CLOUD_RAIN "\uE03C"   // cloud-rain
#define ICON_CLOUD_SNOW "\uE03D"   // cloud-snow
#define ICON_CLOUD "\uE03E"   // cloud
#define ICON_CODE "\uE03F"   // code
#define ICON_COMMAND "\uE040"   // command
#define ICON_COMPASS "\uE041"   // compass
#define ICON_COPY "\uE042"   // copy
#define ICON_CORNER_DOWN_LEFT "\uE043"   // corner-down-left
#define ICON_CORNER_DOWN_RIGHT "\uE044"   // corner-down-right
#define ICON_CORNER_LEFT_DOWN "\uE045"   // corner-left-down
#define ICON_CORNER_LEFT_UP "\uE046"   // corner-left-up
#define ICON_CORNER_RIGHT_DOWN "\uE047"   // corner-right-down
#define ICON_CORNER_RIGHT_UP "\uE048"   // corner-right-up
#define ICON_CORNER_UP_LEFT "\uE049"   // corner-up-left
#define ICON_CORNER_UP_RIGHT "\uE04A"   // corner-up-right
#define ICON_CPU "\uE04B"   // cpu
#define ICON_CREDIT_CARD "\uE04C"   // credit-card
#define ICON_CROP "\uE04D"   // crop
#define ICON_CROSSHAIR "\uE04E"   // crosshair
#define ICON_DATABASE "\uE04F"   // database
#define ICON_DELETE "\uE050"   // delete
#define ICON_DISC "\uE051"   // disc
#define ICON_DOLLAR_SIGN "\uE052"   // dollar-sign
#define ICON_DOWNLOAD_CLOUD "\uE053"   // download-cloud
#define ICON_DOWNLOAD "\uE054"   // download
#define ICON_DROPLET "\uE055"   // droplet
#define ICON_EDIT_2 "\uE056"   // edit-2
#define ICON_EDIT_3 "\uE057"   // edit-3
#define ICON_EDIT "\uE058"   // edit
#define ICON_EXTERNAL_LINK "\uE059"   // external-link
#define ICON_EYE_OFF "\uE05A"   // eye-off
#define ICON_EYE "\uE05B"   // eye
#define ICON_FAST_FORWARD "\uE05C"   // fast-forward
#define ICON_FEATHER "\uE05D"   // feather
#define ICON_FILE_MINUS "\uE05E"   // file-minus
#define ICON_FILE_PLUS "\uE05F"   // file-plus
#define ICON_FILE_TEXT "\uE060"   // file-text
#define ICON_FILE "\uE061"   // file
#define ICON_FILM "\uE062"   // film
#define ICON_FILTER "\uE063"   // filter
#define ICON_FLAG "\uE064"   // flag
#define ICON_FOLDER_MINUS "\uE065"   // folder-minus
#define ICON_FOLDER_PLUS "\uE066"   // folder-plus
#define ICON_FOLDER "\uE067"   // folder
#define ICON_GIFT "\uE068"   // gift
#define ICON_GIT_BRANCH "\uE069"   // git-branch
#define ICON_GIT_COMMIT "\uE06A"   // git-commit
#define ICON_GIT_MERGE "\uE06B"   // git-merge
#define ICON_GIT_PULL_REQUEST "\uE06C"   // git-pull-request
#define ICON_GLOBE "\uE06D"   // globe
#define ICON_GRID "\uE06E"   // grid
#define ICON_HARD_DRIVE "\uE06F"   // hard-drive
#define ICON_HASH "\uE070"   // hash
#define ICON_HEADPHONES "\uE071"   // headphones
#define ICON_HEART "\uE072"   // heart
#define ICON_HELP_CIRCLE "\uE073"   // help-circle
#define ICON_HOME "\uE074"   // home
#define ICON_IMAGE "\uE075"   // image
#define ICON_INBOX "\uE076"   // inbox
#define ICON_INFO "\uE077"   // info
#define ICON_ITALIC "\uE078"   // italic
#define ICON_LAYERS "\uE079"   // layers
#define ICON_LAYOUT "\uE07A"   // layout
#define ICON_LIFE_BUOY "\uE07B"   // life-buoy
#define ICON_LINK_2 "\uE07C"   // link-2
#define ICON_LINK "\uE07D"   // link
#define ICON_LIST "\uE07E"   // list
#define ICON_LOADER "\uE07F"   // loader
#define ICON_LOCK "\uE080"   // lock
#define ICON_LOG_IN "\uE081"   // log-in
#define ICON_LOG_OUT "\uE082"   // log-out
#define ICON_MAIL "\uE083"   // mail
#define ICON_MAP_PIN "\uE084"   // map-pin
#define ICON_MAP "\uE085"   // map
#define ICON_MAXIMIZE_2 "\uE086"   // maximize-2
#define ICON_MAXIMIZE "\uE087"   // maximize
#define ICON_MENU "\uE088"   // menu
#define ICON_MESSAGE_CIRCLE "\uE089"   // message-circle
#define ICON_MESSAGE_SQUARE "\uE08A"   // message-square
#define ICON_MIC_OFF "\uE08B"   // mic-off
#define ICON_MIC "\uE08C"   // mic
#define ICON_MINIMIZE_2 "\uE08D"   // minimize-2
#define ICON_MINIMIZE "\uE08E"   // minimize
#define ICON_MINUS_CIRCLE "\uE08F"   // minus-circle
#define ICON_MINUS_SQUARE "\uE090"   // minus-square
#define ICON_MINUS "\uE091"   // minus
#define ICON_MONITOR "\uE092"   // monitor
#define ICON_MOON "\uE093"   // moon
#define ICON_MORE_HORIZONTAL "\uE094"   // more-horizontal
#define ICON_MORE_VERTICAL "\uE095"   // more-vertical
#define ICON_MOVE "\uE096"   // move
#define ICON_MUSIC "\uE097"   // music
#define ICON_NAVIGATION_2 "\uE098"   // navigation-2
#define ICON_NAVIGATION "\uE099"   // navigation
#define ICON_OCTAGON "\uE09A"   // octagon
#define ICON_PACKAGE "\uE09B"   // package
#define ICON_PAPERCLIP "\uE09C"   // paperclip
#define ICON_PAUSE_CIRCLE "\uE09D"   // pause-circle
#define ICON_PAUSE "\uE09E"   // pause
#define ICON_PERCENT "\uE09F"   // percent
#define ICON_PHONE_CALL "\uE0A0"   // phone-call
#define ICON_PHONE_FORWARDED "\uE0A1"   // phone-forwarded
#define ICON_PHONE_INCOMING "\uE0A2"   // phone-incoming
#define ICON_PHONE_MISSED "\uE0A3"   // phone-missed
#define ICON_PHONE_OFF "\uE0A4"   // phone-off
#define ICON_PHONE_OUTGOING "\uE0A5"   // phone-outgoing
#define ICON_PHONE "\uE0A6"   // phone
#define ICON_PIE_CHART "\uE0A7"   // pie-chart
#define ICON_PLAY_CIRCLE "\uE0A8"   // play-circle
#define ICON_PLAY "\uE0A9"   // play
#define ICON_PLUS_CIRCLE "\uE0AA"   // plus-circle
#define ICON_PLUS_SQUARE "\uE0AB"   // plus-square
#define ICON_PLUS "\uE0AC"   // plus
#define ICON_POWER "\uE0AD"   // power
#define ICON_PRINTER "\uE0AE"   // printer
#define ICON_RADIO "\uE0AF"   // radio
#define ICON_REFRESH_CCW "\uE0B0"   // refresh-ccw
#define ICON_REFRESH_CW "\uE0B1"   // refresh-cw
#define ICON_REPEAT "\uE0B2"   // repeat
#define ICON_REWIND "\uE0B3"   // rewind
#define ICON_ROTATE_CCW "\uE0B4"   // rotate-ccw
#define ICON_ROTATE_CW "\uE0B5"   // rotate-cw
#define ICON_RSS "\uE0B6"   // rss
#define ICON_SAVE "\uE0B7"   // save
#define ICON_SCISSORS "\uE0B8"   // scissors
#define ICON_SEARCH "\uE0B9"   // search
#define ICON_SEND "\uE0BA"   // send
#define ICON_SERVER "\uE0BB"   // server
#define ICON_SETTINGS "\uE0BC"   // settings
#define ICON_SHARE_2 "\uE0BD"   // share-2
#define ICON_SHARE "\uE0BE"   // share
#define ICON_SHIELD_OFF "\uE0BF"   // shield-off
#define ICON_SHIELD "\uE0C0"   // shield
#define ICON_SHOPPING_BAG "\uE0C1"   // shopping-bag
#define ICON_SHOPPING_CART "\uE0C2"   // shopping-cart
#define ICON_SHUFFLE "\uE0C3"   // shuffle
#define ICON_SIDEBAR "\uE0C4"   // sidebar
#define ICON_SKIP_BACK "\uE0C5"   // skip-back
#define ICON_SKIP_FORWARD "\uE0C6"   // skip-forward
#define ICON_SLASH "\uE0C7"   // slash
#define ICON_SLIDERS "\uE0C8"   // sliders
#define ICON_SMARTPHONE "\uE0C9"   // smartphone
#define ICON_SPEAKER "\uE0CA"   // speaker
#define ICON_SQUARE "\uE0CB"   // square
#define ICON_STAR "\uE0CC"   // star
#define ICON_STOP_CIRCLE "\uE0CD"   // stop-circle
#define ICON_SUN "\uE0CE"   // sun
#define ICON_SUNRISE "\uE0CF"   // sunrise
#define ICON_SUNSET "\uE0D0"   // sunset
#define ICON_TABLET "\uE0D1"   // tablet
#define ICON_TAG "\uE0D2"   // tag
#define ICON_TARGET "\uE0D3"   // target
#define ICON_TERMINAL "\uE0D4"   // terminal
#define ICON_THERMOMETER "\uE0D5"   // thermometer
#define ICON_THUMBS_DOWN "\uE0D6"   // thumbs-down
#define ICON_THUMBS_UP "\uE0D7"   // thumbs-up
#define ICON_TOGGLE_LEFT "\uE0D8"   // toggle-left
#define ICON_TOGGLE_RIGHT "\uE0D9"   // toggle-right
#define ICON_TRASH_2 "\uE0DA"   // trash-2
#define ICON_TRASH "\uE0DB"   // trash
#define ICON_TRENDING_DOWN "\uE0DC"   // trending-down
#define ICON_TRENDING_UP "\uE0DD"   // trending-up
#define ICON_TRIANGLE "\uE0DE"   // triangle
#define ICON_TRUCK "\uE0DF"   // truck
#define ICON_TV "\uE0E0"   // tv
#define ICON_TYPE "\uE0E1"   // type
#define ICON_UMBRELLA "\uE0E2"   // umbrella
#define ICON_UNDERLINE "\uE0E3"   // underline
#define ICON_UNLOCK "\uE0E4"   // unlock
#define ICON_UPLOAD_CLOUD "\uE0E5"   // upload-cloud
#define ICON_UPLOAD "\uE0E6"   // upload
#define ICON_USER_CHECK "\uE0E7"   // user-check
#define ICON_USER_MINUS "\uE0E8"   // user-minus
#define ICON_USER_PLUS "\uE0E9"   // user-plus
#define ICON_USER_X "\uE0EA"   // user-x
#define ICON_USER "\uE0EB"   // user
#define ICON_USERS "\uE0EC"   // users
#define ICON_VIDEO_OFF "\uE0ED"   // video-off
#define ICON_VIDEO "\uE0EE"   // video
#define ICON_VOICEMAIL "\uE0EF"   // voicemail
#define ICON_VOLUME_1 "\uE0F0"   // volume-1
#define ICON_VOLUME_2 "\uE0F1"   // volume-2
#define ICON_VOLUME_X "\uE0F2"   // volume-x
#define ICON_VOLUME "\uE0F3"   // volume
#define ICON_WATCH "\uE0F4"   // watch
#define ICON_WIFI_OFF "\uE0F5"   // wifi-off
#define ICON_WIFI "\uE0F6"   // wifi
#define ICON_WIND "\uE0F7"   // wind
#define ICON_X_CIRCLE "\uE0F8"   // x-circle
#define ICON_X_SQUARE "\uE0F9"   // x-square
#define ICON_X "\uE0FA"   // x
#define ICON_ZAP_OFF "\uE0FB"   // zap-off
#define ICON_ZAP "\uE0FC"   // zap
#define ICON_ZOOM_IN "\uE0FD"   // zoom-in
#define ICON_ZOOM_OUT "\uE0FE"   // zoom-out

// End of icon definitions
