// AUTO-GENERATED from OpenFontIcons.ttx
#pragma once

// Private-Use icons U+E000–U+F8FF
#define ICON_MIN_OF 0xE000   // Icon start range
#define ICON_MAX_OF 0xF8FF   // Icon end range

#define ICON_ACTIVITY u8"\uE000"   // activity
#define ICON_AIRPLAY u8"\uE001"   // airplay
#define ICON_ALERT_CIRCLE u8"\uE002"   // alert-circle
#define ICON_ALERT_OCTAGON u8"\uE003"   // alert-octagon
#define ICON_ALERT_TRIANGLE u8"\uE004"   // alert-triangle
#define ICON_ALIGN_CENTER u8"\uE005"   // align-center
#define ICON_ALIGN_JUSTIFY u8"\uE006"   // align-justify
#define ICON_ALIGN_LEFT u8"\uE007"   // align-left
#define ICON_ALIGN_RIGHT u8"\uE008"   // align-right
#define ICON_ANCHOR u8"\uE009"   // anchor
#define ICON_APERTURE u8"\uE00A"   // aperture
#define ICON_ARCHIVE u8"\uE00B"   // archive
#define ICON_ARROW_DOWN_CIRCLE u8"\uE00C"   // arrow-down-circle
#define ICON_ARROW_DOWN_LEFT u8"\uE00D"   // arrow-down-left
#define ICON_ARROW_DOWN_RIGHT u8"\uE00E"   // arrow-down-right
#define ICON_ARROW_DOWN u8"\uE00F"   // arrow-down
#define ICON_ARROW_LEFT_CIRCLE u8"\uE010"   // arrow-left-circle
#define ICON_ARROW_LEFT u8"\uE011"   // arrow-left
#define ICON_ARROW_RIGHT_CIRCLE u8"\uE012"   // arrow-right-circle
#define ICON_ARROW_RIGHT u8"\uE013"   // arrow-right
#define ICON_ARROW_UP_CIRCLE u8"\uE014"   // arrow-up-circle
#define ICON_ARROW_UP_LEFT u8"\uE015"   // arrow-up-left
#define ICON_ARROW_UP_RIGHT u8"\uE016"   // arrow-up-right
#define ICON_ARROW_UP u8"\uE017"   // arrow-up
#define ICON_AT_SIGN u8"\uE018"   // at-sign
#define ICON_AWARD u8"\uE019"   // award
#define ICON_BAR_CHART_2 u8"\uE01A"   // bar-chart-2
#define ICON_BAR_CHART u8"\uE01B"   // bar-chart
#define ICON_BATTERY_CHARGING u8"\uE01C"   // battery-charging
#define ICON_BATTERY u8"\uE01D"   // battery
#define ICON_BELL_OFF u8"\uE01E"   // bell-off
#define ICON_BELL u8"\uE01F"   // bell
#define ICON_BLUETOOTH u8"\uE020"   // bluetooth
#define ICON_BOLD u8"\uE021"   // bold
#define ICON_BOOK_OPEN u8"\uE022"   // book-open
#define ICON_BOOK u8"\uE023"   // book
#define ICON_BOOKMARK u8"\uE024"   // bookmark
#define ICON_BOX u8"\uE025"   // box
#define ICON_BRIEFCASE u8"\uE026"   // briefcase
#define ICON_CALENDAR u8"\uE027"   // calendar
#define ICON_CAMERA_OFF u8"\uE028"   // camera-off
#define ICON_CAMERA u8"\uE029"   // camera
#define ICON_CAST u8"\uE02A"   // cast
#define ICON_CHECK_CIRCLE u8"\uE02B"   // check-circle
#define ICON_CHECK_SQUARE u8"\uE02C"   // check-square
#define ICON_CHECK u8"\uE02D"   // check
#define ICON_CHEVRON_DOWN u8"\uE02E"   // chevron-down
#define ICON_CHEVRON_LEFT u8"\uE02F"   // chevron-left
#define ICON_CHEVRON_RIGHT u8"\uE030"   // chevron-right
#define ICON_CHEVRON_UP u8"\uE031"   // chevron-up
#define ICON_CHEVRONS_DOWN u8"\uE032"   // chevrons-down
#define ICON_CHEVRONS_LEFT u8"\uE033"   // chevrons-left
#define ICON_CHEVRONS_RIGHT u8"\uE034"   // chevrons-right
#define ICON_CHEVRONS_UP u8"\uE035"   // chevrons-up
#define ICON_CIRCLE u8"\uE036"   // circle
#define ICON_CLIPBOARD u8"\uE037"   // clipboard
#define ICON_CLOCK u8"\uE038"   // clock
#define ICON_CLOUD_DRIZZLE u8"\uE039"   // cloud-drizzle
#define ICON_CLOUD_LIGHTNING u8"\uE03A"   // cloud-lightning
#define ICON_CLOUD_OFF u8"\uE03B"   // cloud-off
#define ICON_CLOUD_RAIN u8"\uE03C"   // cloud-rain
#define ICON_CLOUD_SNOW u8"\uE03D"   // cloud-snow
#define ICON_CLOUD u8"\uE03E"   // cloud
#define ICON_CODE u8"\uE03F"   // code
#define ICON_COMMAND u8"\uE040"   // command
#define ICON_COMPASS u8"\uE041"   // compass
#define ICON_COPY u8"\uE042"   // copy
#define ICON_CORNER_DOWN_LEFT u8"\uE043"   // corner-down-left
#define ICON_CORNER_DOWN_RIGHT u8"\uE044"   // corner-down-right
#define ICON_CORNER_LEFT_DOWN u8"\uE045"   // corner-left-down
#define ICON_CORNER_LEFT_UP u8"\uE046"   // corner-left-up
#define ICON_CORNER_RIGHT_DOWN u8"\uE047"   // corner-right-down
#define ICON_CORNER_RIGHT_UP u8"\uE048"   // corner-right-up
#define ICON_CORNER_UP_LEFT u8"\uE049"   // corner-up-left
#define ICON_CORNER_UP_RIGHT u8"\uE04A"   // corner-up-right
#define ICON_CPU u8"\uE04B"   // cpu
#define ICON_CREDIT_CARD u8"\uE04C"   // credit-card
#define ICON_CROP u8"\uE04D"   // crop
#define ICON_CROSSHAIR u8"\uE04E"   // crosshair
#define ICON_DATABASE u8"\uE04F"   // database
#define ICON_DELETE u8"\uE050"   // delete
#define ICON_DISC u8"\uE051"   // disc
#define ICON_DOLLAR_SIGN u8"\uE052"   // dollar-sign
#define ICON_DOWNLOAD_CLOUD u8"\uE053"   // download-cloud
#define ICON_DOWNLOAD u8"\uE054"   // download
#define ICON_DROPLET u8"\uE055"   // droplet
#define ICON_EDIT_2 u8"\uE056"   // edit-2
#define ICON_EDIT_3 u8"\uE057"   // edit-3
#define ICON_EDIT u8"\uE058"   // edit
#define ICON_EXTERNAL_LINK u8"\uE059"   // external-link
#define ICON_EYE_OFF u8"\uE05A"   // eye-off
#define ICON_EYE u8"\uE05B"   // eye
#define ICON_FAST_FORWARD u8"\uE05C"   // fast-forward
#define ICON_FEATHER u8"\uE05D"   // feather
#define ICON_FILE_MINUS u8"\uE05E"   // file-minus
#define ICON_FILE_PLUS u8"\uE05F"   // file-plus
#define ICON_FILE_TEXT u8"\uE060"   // file-text
#define ICON_FILE u8"\uE061"   // file
#define ICON_FILM u8"\uE062"   // film
#define ICON_FILTER u8"\uE063"   // filter
#define ICON_FLAG u8"\uE064"   // flag
#define ICON_FOLDER_MINUS u8"\uE065"   // folder-minus
#define ICON_FOLDER_PLUS u8"\uE066"   // folder-plus
#define ICON_FOLDER u8"\uE067"   // folder
#define ICON_GIFT u8"\uE068"   // gift
#define ICON_GIT_BRANCH u8"\uE069"   // git-branch
#define ICON_GIT_COMMIT u8"\uE06A"   // git-commit
#define ICON_GIT_MERGE u8"\uE06B"   // git-merge
#define ICON_GIT_PULL_REQUEST u8"\uE06C"   // git-pull-request
#define ICON_GLOBE u8"\uE06D"   // globe
#define ICON_GRID u8"\uE06E"   // grid
#define ICON_HARD_DRIVE u8"\uE06F"   // hard-drive
#define ICON_HASH u8"\uE070"   // hash
#define ICON_HEADPHONES u8"\uE071"   // headphones
#define ICON_HEART u8"\uE072"   // heart
#define ICON_HELP_CIRCLE u8"\uE073"   // help-circle
#define ICON_HOME u8"\uE074"   // home
#define ICON_IMAGE u8"\uE075"   // image
#define ICON_INBOX u8"\uE076"   // inbox
#define ICON_INFO u8"\uE077"   // info
#define ICON_ITALIC u8"\uE078"   // italic
#define ICON_LAYERS u8"\uE079"   // layers
#define ICON_LAYOUT u8"\uE07A"   // layout
#define ICON_LIFE_BUOY u8"\uE07B"   // life-buoy
#define ICON_LINK_2 u8"\uE07C"   // link-2
#define ICON_LINK u8"\uE07D"   // link
#define ICON_LIST u8"\uE07E"   // list
#define ICON_LOADER u8"\uE07F"   // loader
#define ICON_LOCK u8"\uE080"   // lock
#define ICON_LOG_IN u8"\uE081"   // log-in
#define ICON_LOG_OUT u8"\uE082"   // log-out
#define ICON_MAIL u8"\uE083"   // mail
#define ICON_MAP_PIN u8"\uE084"   // map-pin
#define ICON_MAP u8"\uE085"   // map
#define ICON_MAXIMIZE_2 u8"\uE086"   // maximize-2
#define ICON_MAXIMIZE u8"\uE087"   // maximize
#define ICON_MENU u8"\uE088"   // menu
#define ICON_MESSAGE_CIRCLE u8"\uE089"   // message-circle
#define ICON_MESSAGE_SQUARE u8"\uE08A"   // message-square
#define ICON_MIC_OFF u8"\uE08B"   // mic-off
#define ICON_MIC u8"\uE08C"   // mic
#define ICON_MINIMIZE_2 u8"\uE08D"   // minimize-2
#define ICON_MINIMIZE u8"\uE08E"   // minimize
#define ICON_MINUS_CIRCLE u8"\uE08F"   // minus-circle
#define ICON_MINUS_SQUARE u8"\uE090"   // minus-square
#define ICON_MINUS u8"\uE091"   // minus
#define ICON_MONITOR u8"\uE092"   // monitor
#define ICON_MOON u8"\uE093"   // moon
#define ICON_MORE_HORIZONTAL u8"\uE094"   // more-horizontal
#define ICON_MORE_VERTICAL u8"\uE095"   // more-vertical
#define ICON_MOVE u8"\uE096"   // move
#define ICON_MUSIC u8"\uE097"   // music
#define ICON_NAVIGATION_2 u8"\uE098"   // navigation-2
#define ICON_NAVIGATION u8"\uE099"   // navigation
#define ICON_OCTAGON u8"\uE09A"   // octagon
#define ICON_PACKAGE u8"\uE09B"   // package
#define ICON_PAPERCLIP u8"\uE09C"   // paperclip
#define ICON_PAUSE_CIRCLE u8"\uE09D"   // pause-circle
#define ICON_PAUSE u8"\uE09E"   // pause
#define ICON_PERCENT u8"\uE09F"   // percent
#define ICON_PHONE_CALL u8"\uE0A0"   // phone-call
#define ICON_PHONE_FORWARDED u8"\uE0A1"   // phone-forwarded
#define ICON_PHONE_INCOMING u8"\uE0A2"   // phone-incoming
#define ICON_PHONE_MISSED u8"\uE0A3"   // phone-missed
#define ICON_PHONE_OFF u8"\uE0A4"   // phone-off
#define ICON_PHONE_OUTGOING u8"\uE0A5"   // phone-outgoing
#define ICON_PHONE u8"\uE0A6"   // phone
#define ICON_PIE_CHART u8"\uE0A7"   // pie-chart
#define ICON_PLAY_CIRCLE u8"\uE0A8"   // play-circle
#define ICON_PLAY u8"\uE0A9"   // play
#define ICON_PLUS_CIRCLE u8"\uE0AA"   // plus-circle
#define ICON_PLUS_SQUARE u8"\uE0AB"   // plus-square
#define ICON_PLUS u8"\uE0AC"   // plus
#define ICON_POWER u8"\uE0AD"   // power
#define ICON_PRINTER u8"\uE0AE"   // printer
#define ICON_RADIO u8"\uE0AF"   // radio
#define ICON_REFRESH_CCW u8"\uE0B0"   // refresh-ccw
#define ICON_REFRESH_CW u8"\uE0B1"   // refresh-cw
#define ICON_REPEAT u8"\uE0B2"   // repeat
#define ICON_REWIND u8"\uE0B3"   // rewind
#define ICON_ROTATE_CCW u8"\uE0B4"   // rotate-ccw
#define ICON_ROTATE_CW u8"\uE0B5"   // rotate-cw
#define ICON_RSS u8"\uE0B6"   // rss
#define ICON_SAVE u8"\uE0B7"   // save
#define ICON_SCISSORS u8"\uE0B8"   // scissors
#define ICON_SEARCH u8"\uE0B9"   // search
#define ICON_SEND u8"\uE0BA"   // send
#define ICON_SERVER u8"\uE0BB"   // server
#define ICON_SETTINGS u8"\uE0BC"   // settings
#define ICON_SHARE_2 u8"\uE0BD"   // share-2
#define ICON_SHARE u8"\uE0BE"   // share
#define ICON_SHIELD_OFF u8"\uE0BF"   // shield-off
#define ICON_SHIELD u8"\uE0C0"   // shield
#define ICON_SHOPPING_BAG u8"\uE0C1"   // shopping-bag
#define ICON_SHOPPING_CART u8"\uE0C2"   // shopping-cart
#define ICON_SHUFFLE u8"\uE0C3"   // shuffle
#define ICON_SIDEBAR u8"\uE0C4"   // sidebar
#define ICON_SKIP_BACK u8"\uE0C5"   // skip-back
#define ICON_SKIP_FORWARD u8"\uE0C6"   // skip-forward
#define ICON_SLASH u8"\uE0C7"   // slash
#define ICON_SLIDERS u8"\uE0C8"   // sliders
#define ICON_SMARTPHONE u8"\uE0C9"   // smartphone
#define ICON_SPEAKER u8"\uE0CA"   // speaker
#define ICON_SQUARE u8"\uE0CB"   // square
#define ICON_STAR u8"\uE0CC"   // star
#define ICON_STOP_CIRCLE u8"\uE0CD"   // stop-circle
#define ICON_SUN u8"\uE0CE"   // sun
#define ICON_SUNRISE u8"\uE0CF"   // sunrise
#define ICON_SUNSET u8"\uE0D0"   // sunset
#define ICON_TABLET u8"\uE0D1"   // tablet
#define ICON_TAG u8"\uE0D2"   // tag
#define ICON_TARGET u8"\uE0D3"   // target
#define ICON_TERMINAL u8"\uE0D4"   // terminal
#define ICON_THERMOMETER u8"\uE0D5"   // thermometer
#define ICON_THUMBS_DOWN u8"\uE0D6"   // thumbs-down
#define ICON_THUMBS_UP u8"\uE0D7"   // thumbs-up
#define ICON_TOGGLE_LEFT u8"\uE0D8"   // toggle-left
#define ICON_TOGGLE_RIGHT u8"\uE0D9"   // toggle-right
#define ICON_TRASH_2 u8"\uE0DA"   // trash-2
#define ICON_TRASH u8"\uE0DB"   // trash
#define ICON_TRENDING_DOWN u8"\uE0DC"   // trending-down
#define ICON_TRENDING_UP u8"\uE0DD"   // trending-up
#define ICON_TRIANGLE u8"\uE0DE"   // triangle
#define ICON_TRUCK u8"\uE0DF"   // truck
#define ICON_TV u8"\uE0E0"   // tv
#define ICON_TYPE u8"\uE0E1"   // type
#define ICON_UMBRELLA u8"\uE0E2"   // umbrella
#define ICON_UNDERLINE u8"\uE0E3"   // underline
#define ICON_UNLOCK u8"\uE0E4"   // unlock
#define ICON_UPLOAD_CLOUD u8"\uE0E5"   // upload-cloud
#define ICON_UPLOAD u8"\uE0E6"   // upload
#define ICON_USER_CHECK u8"\uE0E7"   // user-check
#define ICON_USER_MINUS u8"\uE0E8"   // user-minus
#define ICON_USER_PLUS u8"\uE0E9"   // user-plus
#define ICON_USER_X u8"\uE0EA"   // user-x
#define ICON_USER u8"\uE0EB"   // user
#define ICON_USERS u8"\uE0EC"   // users
#define ICON_VIDEO_OFF u8"\uE0ED"   // video-off
#define ICON_VIDEO u8"\uE0EE"   // video
#define ICON_VOICEMAIL u8"\uE0EF"   // voicemail
#define ICON_VOLUME_1 u8"\uE0F0"   // volume-1
#define ICON_VOLUME_2 u8"\uE0F1"   // volume-2
#define ICON_VOLUME_X u8"\uE0F2"   // volume-x
#define ICON_VOLUME u8"\uE0F3"   // volume
#define ICON_WATCH u8"\uE0F4"   // watch
#define ICON_WIFI_OFF u8"\uE0F5"   // wifi-off
#define ICON_WIFI u8"\uE0F6"   // wifi
#define ICON_WIND u8"\uE0F7"   // wind
#define ICON_X_CIRCLE u8"\uE0F8"   // x-circle
#define ICON_X_SQUARE u8"\uE0F9"   // x-square
#define ICON_X u8"\uE0FA"   // x
#define ICON_ZAP_OFF u8"\uE0FB"   // zap-off
#define ICON_ZAP u8"\uE0FC"   // zap
#define ICON_ZOOM_IN u8"\uE0FD"   // zoom-in
#define ICON_ZOOM_OUT u8"\uE0FE"   // zoom-out
#define ICON_ACTIVITY u8"\uE000"   // activity
#define ICON_AIRPLAY u8"\uE001"   // airplay
#define ICON_ALERT_CIRCLE u8"\uE002"   // alert-circle
#define ICON_ALERT_OCTAGON u8"\uE003"   // alert-octagon
#define ICON_ALERT_TRIANGLE u8"\uE004"   // alert-triangle
#define ICON_ALIGN_CENTER u8"\uE005"   // align-center
#define ICON_ALIGN_JUSTIFY u8"\uE006"   // align-justify
#define ICON_ALIGN_LEFT u8"\uE007"   // align-left
#define ICON_ALIGN_RIGHT u8"\uE008"   // align-right
#define ICON_ANCHOR u8"\uE009"   // anchor
#define ICON_APERTURE u8"\uE00A"   // aperture
#define ICON_ARCHIVE u8"\uE00B"   // archive
#define ICON_ARROW_DOWN_CIRCLE u8"\uE00C"   // arrow-down-circle
#define ICON_ARROW_DOWN_LEFT u8"\uE00D"   // arrow-down-left
#define ICON_ARROW_DOWN_RIGHT u8"\uE00E"   // arrow-down-right
#define ICON_ARROW_DOWN u8"\uE00F"   // arrow-down
#define ICON_ARROW_LEFT_CIRCLE u8"\uE010"   // arrow-left-circle
#define ICON_ARROW_LEFT u8"\uE011"   // arrow-left
#define ICON_ARROW_RIGHT_CIRCLE u8"\uE012"   // arrow-right-circle
#define ICON_ARROW_RIGHT u8"\uE013"   // arrow-right
#define ICON_ARROW_UP_CIRCLE u8"\uE014"   // arrow-up-circle
#define ICON_ARROW_UP_LEFT u8"\uE015"   // arrow-up-left
#define ICON_ARROW_UP_RIGHT u8"\uE016"   // arrow-up-right
#define ICON_ARROW_UP u8"\uE017"   // arrow-up
#define ICON_AT_SIGN u8"\uE018"   // at-sign
#define ICON_AWARD u8"\uE019"   // award
#define ICON_BAR_CHART_2 u8"\uE01A"   // bar-chart-2
#define ICON_BAR_CHART u8"\uE01B"   // bar-chart
#define ICON_BATTERY_CHARGING u8"\uE01C"   // battery-charging
#define ICON_BATTERY u8"\uE01D"   // battery
#define ICON_BELL_OFF u8"\uE01E"   // bell-off
#define ICON_BELL u8"\uE01F"   // bell
#define ICON_BLUETOOTH u8"\uE020"   // bluetooth
#define ICON_BOLD u8"\uE021"   // bold
#define ICON_BOOK_OPEN u8"\uE022"   // book-open
#define ICON_BOOK u8"\uE023"   // book
#define ICON_BOOKMARK u8"\uE024"   // bookmark
#define ICON_BOX u8"\uE025"   // box
#define ICON_BRIEFCASE u8"\uE026"   // briefcase
#define ICON_CALENDAR u8"\uE027"   // calendar
#define ICON_CAMERA_OFF u8"\uE028"   // camera-off
#define ICON_CAMERA u8"\uE029"   // camera
#define ICON_CAST u8"\uE02A"   // cast
#define ICON_CHECK_CIRCLE u8"\uE02B"   // check-circle
#define ICON_CHECK_SQUARE u8"\uE02C"   // check-square
#define ICON_CHECK u8"\uE02D"   // check
#define ICON_CHEVRON_DOWN u8"\uE02E"   // chevron-down
#define ICON_CHEVRON_LEFT u8"\uE02F"   // chevron-left
#define ICON_CHEVRON_RIGHT u8"\uE030"   // chevron-right
#define ICON_CHEVRON_UP u8"\uE031"   // chevron-up
#define ICON_CHEVRONS_DOWN u8"\uE032"   // chevrons-down
#define ICON_CHEVRONS_LEFT u8"\uE033"   // chevrons-left
#define ICON_CHEVRONS_RIGHT u8"\uE034"   // chevrons-right
#define ICON_CHEVRONS_UP u8"\uE035"   // chevrons-up
#define ICON_CIRCLE u8"\uE036"   // circle
#define ICON_CLIPBOARD u8"\uE037"   // clipboard
#define ICON_CLOCK u8"\uE038"   // clock
#define ICON_CLOUD_DRIZZLE u8"\uE039"   // cloud-drizzle
#define ICON_CLOUD_LIGHTNING u8"\uE03A"   // cloud-lightning
#define ICON_CLOUD_OFF u8"\uE03B"   // cloud-off
#define ICON_CLOUD_RAIN u8"\uE03C"   // cloud-rain
#define ICON_CLOUD_SNOW u8"\uE03D"   // cloud-snow
#define ICON_CLOUD u8"\uE03E"   // cloud
#define ICON_CODE u8"\uE03F"   // code
#define ICON_COMMAND u8"\uE040"   // command
#define ICON_COMPASS u8"\uE041"   // compass
#define ICON_COPY u8"\uE042"   // copy
#define ICON_CORNER_DOWN_LEFT u8"\uE043"   // corner-down-left
#define ICON_CORNER_DOWN_RIGHT u8"\uE044"   // corner-down-right
#define ICON_CORNER_LEFT_DOWN u8"\uE045"   // corner-left-down
#define ICON_CORNER_LEFT_UP u8"\uE046"   // corner-left-up
#define ICON_CORNER_RIGHT_DOWN u8"\uE047"   // corner-right-down
#define ICON_CORNER_RIGHT_UP u8"\uE048"   // corner-right-up
#define ICON_CORNER_UP_LEFT u8"\uE049"   // corner-up-left
#define ICON_CORNER_UP_RIGHT u8"\uE04A"   // corner-up-right
#define ICON_CPU u8"\uE04B"   // cpu
#define ICON_CREDIT_CARD u8"\uE04C"   // credit-card
#define ICON_CROP u8"\uE04D"   // crop
#define ICON_CROSSHAIR u8"\uE04E"   // crosshair
#define ICON_DATABASE u8"\uE04F"   // database
#define ICON_DELETE u8"\uE050"   // delete
#define ICON_DISC u8"\uE051"   // disc
#define ICON_DOLLAR_SIGN u8"\uE052"   // dollar-sign
#define ICON_DOWNLOAD_CLOUD u8"\uE053"   // download-cloud
#define ICON_DOWNLOAD u8"\uE054"   // download
#define ICON_DROPLET u8"\uE055"   // droplet
#define ICON_EDIT_2 u8"\uE056"   // edit-2
#define ICON_EDIT_3 u8"\uE057"   // edit-3
#define ICON_EDIT u8"\uE058"   // edit
#define ICON_EXTERNAL_LINK u8"\uE059"   // external-link
#define ICON_EYE_OFF u8"\uE05A"   // eye-off
#define ICON_EYE u8"\uE05B"   // eye
#define ICON_FAST_FORWARD u8"\uE05C"   // fast-forward
#define ICON_FEATHER u8"\uE05D"   // feather
#define ICON_FILE_MINUS u8"\uE05E"   // file-minus
#define ICON_FILE_PLUS u8"\uE05F"   // file-plus
#define ICON_FILE_TEXT u8"\uE060"   // file-text
#define ICON_FILE u8"\uE061"   // file
#define ICON_FILM u8"\uE062"   // film
#define ICON_FILTER u8"\uE063"   // filter
#define ICON_FLAG u8"\uE064"   // flag
#define ICON_FOLDER_MINUS u8"\uE065"   // folder-minus
#define ICON_FOLDER_PLUS u8"\uE066"   // folder-plus
#define ICON_FOLDER u8"\uE067"   // folder
#define ICON_GIFT u8"\uE068"   // gift
#define ICON_GIT_BRANCH u8"\uE069"   // git-branch
#define ICON_GIT_COMMIT u8"\uE06A"   // git-commit
#define ICON_GIT_MERGE u8"\uE06B"   // git-merge
#define ICON_GIT_PULL_REQUEST u8"\uE06C"   // git-pull-request
#define ICON_GLOBE u8"\uE06D"   // globe
#define ICON_GRID u8"\uE06E"   // grid
#define ICON_HARD_DRIVE u8"\uE06F"   // hard-drive
#define ICON_HASH u8"\uE070"   // hash
#define ICON_HEADPHONES u8"\uE071"   // headphones
#define ICON_HEART u8"\uE072"   // heart
#define ICON_HELP_CIRCLE u8"\uE073"   // help-circle
#define ICON_HOME u8"\uE074"   // home
#define ICON_IMAGE u8"\uE075"   // image
#define ICON_INBOX u8"\uE076"   // inbox
#define ICON_INFO u8"\uE077"   // info
#define ICON_ITALIC u8"\uE078"   // italic
#define ICON_LAYERS u8"\uE079"   // layers
#define ICON_LAYOUT u8"\uE07A"   // layout
#define ICON_LIFE_BUOY u8"\uE07B"   // life-buoy
#define ICON_LINK_2 u8"\uE07C"   // link-2
#define ICON_LINK u8"\uE07D"   // link
#define ICON_LIST u8"\uE07E"   // list
#define ICON_LOADER u8"\uE07F"   // loader
#define ICON_LOCK u8"\uE080"   // lock
#define ICON_LOG_IN u8"\uE081"   // log-in
#define ICON_LOG_OUT u8"\uE082"   // log-out
#define ICON_MAIL u8"\uE083"   // mail
#define ICON_MAP_PIN u8"\uE084"   // map-pin
#define ICON_MAP u8"\uE085"   // map
#define ICON_MAXIMIZE_2 u8"\uE086"   // maximize-2
#define ICON_MAXIMIZE u8"\uE087"   // maximize
#define ICON_MENU u8"\uE088"   // menu
#define ICON_MESSAGE_CIRCLE u8"\uE089"   // message-circle
#define ICON_MESSAGE_SQUARE u8"\uE08A"   // message-square
#define ICON_MIC_OFF u8"\uE08B"   // mic-off
#define ICON_MIC u8"\uE08C"   // mic
#define ICON_MINIMIZE_2 u8"\uE08D"   // minimize-2
#define ICON_MINIMIZE u8"\uE08E"   // minimize
#define ICON_MINUS_CIRCLE u8"\uE08F"   // minus-circle
#define ICON_MINUS_SQUARE u8"\uE090"   // minus-square
#define ICON_MINUS u8"\uE091"   // minus
#define ICON_MONITOR u8"\uE092"   // monitor
#define ICON_MOON u8"\uE093"   // moon
#define ICON_MORE_HORIZONTAL u8"\uE094"   // more-horizontal
#define ICON_MORE_VERTICAL u8"\uE095"   // more-vertical
#define ICON_MOVE u8"\uE096"   // move
#define ICON_MUSIC u8"\uE097"   // music
#define ICON_NAVIGATION_2 u8"\uE098"   // navigation-2
#define ICON_NAVIGATION u8"\uE099"   // navigation
#define ICON_OCTAGON u8"\uE09A"   // octagon
#define ICON_PACKAGE u8"\uE09B"   // package
#define ICON_PAPERCLIP u8"\uE09C"   // paperclip
#define ICON_PAUSE_CIRCLE u8"\uE09D"   // pause-circle
#define ICON_PAUSE u8"\uE09E"   // pause
#define ICON_PERCENT u8"\uE09F"   // percent
#define ICON_PHONE_CALL u8"\uE0A0"   // phone-call
#define ICON_PHONE_FORWARDED u8"\uE0A1"   // phone-forwarded
#define ICON_PHONE_INCOMING u8"\uE0A2"   // phone-incoming
#define ICON_PHONE_MISSED u8"\uE0A3"   // phone-missed
#define ICON_PHONE_OFF u8"\uE0A4"   // phone-off
#define ICON_PHONE_OUTGOING u8"\uE0A5"   // phone-outgoing
#define ICON_PHONE u8"\uE0A6"   // phone
#define ICON_PIE_CHART u8"\uE0A7"   // pie-chart
#define ICON_PLAY_CIRCLE u8"\uE0A8"   // play-circle
#define ICON_PLAY u8"\uE0A9"   // play
#define ICON_PLUS_CIRCLE u8"\uE0AA"   // plus-circle
#define ICON_PLUS_SQUARE u8"\uE0AB"   // plus-square
#define ICON_PLUS u8"\uE0AC"   // plus
#define ICON_POWER u8"\uE0AD"   // power
#define ICON_PRINTER u8"\uE0AE"   // printer
#define ICON_RADIO u8"\uE0AF"   // radio
#define ICON_REFRESH_CCW u8"\uE0B0"   // refresh-ccw
#define ICON_REFRESH_CW u8"\uE0B1"   // refresh-cw
#define ICON_REPEAT u8"\uE0B2"   // repeat
#define ICON_REWIND u8"\uE0B3"   // rewind
#define ICON_ROTATE_CCW u8"\uE0B4"   // rotate-ccw
#define ICON_ROTATE_CW u8"\uE0B5"   // rotate-cw
#define ICON_RSS u8"\uE0B6"   // rss
#define ICON_SAVE u8"\uE0B7"   // save
#define ICON_SCISSORS u8"\uE0B8"   // scissors
#define ICON_SEARCH u8"\uE0B9"   // search
#define ICON_SEND u8"\uE0BA"   // send
#define ICON_SERVER u8"\uE0BB"   // server
#define ICON_SETTINGS u8"\uE0BC"   // settings
#define ICON_SHARE_2 u8"\uE0BD"   // share-2
#define ICON_SHARE u8"\uE0BE"   // share
#define ICON_SHIELD_OFF u8"\uE0BF"   // shield-off
#define ICON_SHIELD u8"\uE0C0"   // shield
#define ICON_SHOPPING_BAG u8"\uE0C1"   // shopping-bag
#define ICON_SHOPPING_CART u8"\uE0C2"   // shopping-cart
#define ICON_SHUFFLE u8"\uE0C3"   // shuffle
#define ICON_SIDEBAR u8"\uE0C4"   // sidebar
#define ICON_SKIP_BACK u8"\uE0C5"   // skip-back
#define ICON_SKIP_FORWARD u8"\uE0C6"   // skip-forward
#define ICON_SLASH u8"\uE0C7"   // slash
#define ICON_SLIDERS u8"\uE0C8"   // sliders
#define ICON_SMARTPHONE u8"\uE0C9"   // smartphone
#define ICON_SPEAKER u8"\uE0CA"   // speaker
#define ICON_SQUARE u8"\uE0CB"   // square
#define ICON_STAR u8"\uE0CC"   // star
#define ICON_STOP_CIRCLE u8"\uE0CD"   // stop-circle
#define ICON_SUN u8"\uE0CE"   // sun
#define ICON_SUNRISE u8"\uE0CF"   // sunrise
#define ICON_SUNSET u8"\uE0D0"   // sunset
#define ICON_TABLET u8"\uE0D1"   // tablet
#define ICON_TAG u8"\uE0D2"   // tag
#define ICON_TARGET u8"\uE0D3"   // target
#define ICON_TERMINAL u8"\uE0D4"   // terminal
#define ICON_THERMOMETER u8"\uE0D5"   // thermometer
#define ICON_THUMBS_DOWN u8"\uE0D6"   // thumbs-down
#define ICON_THUMBS_UP u8"\uE0D7"   // thumbs-up
#define ICON_TOGGLE_LEFT u8"\uE0D8"   // toggle-left
#define ICON_TOGGLE_RIGHT u8"\uE0D9"   // toggle-right
#define ICON_TRASH_2 u8"\uE0DA"   // trash-2
#define ICON_TRASH u8"\uE0DB"   // trash
#define ICON_TRENDING_DOWN u8"\uE0DC"   // trending-down
#define ICON_TRENDING_UP u8"\uE0DD"   // trending-up
#define ICON_TRIANGLE u8"\uE0DE"   // triangle
#define ICON_TRUCK u8"\uE0DF"   // truck
#define ICON_TV u8"\uE0E0"   // tv
#define ICON_TYPE u8"\uE0E1"   // type
#define ICON_UMBRELLA u8"\uE0E2"   // umbrella
#define ICON_UNDERLINE u8"\uE0E3"   // underline
#define ICON_UNLOCK u8"\uE0E4"   // unlock
#define ICON_UPLOAD_CLOUD u8"\uE0E5"   // upload-cloud
#define ICON_UPLOAD u8"\uE0E6"   // upload
#define ICON_USER_CHECK u8"\uE0E7"   // user-check
#define ICON_USER_MINUS u8"\uE0E8"   // user-minus
#define ICON_USER_PLUS u8"\uE0E9"   // user-plus
#define ICON_USER_X u8"\uE0EA"   // user-x
#define ICON_USER u8"\uE0EB"   // user
#define ICON_USERS u8"\uE0EC"   // users
#define ICON_VIDEO_OFF u8"\uE0ED"   // video-off
#define ICON_VIDEO u8"\uE0EE"   // video
#define ICON_VOICEMAIL u8"\uE0EF"   // voicemail
#define ICON_VOLUME_1 u8"\uE0F0"   // volume-1
#define ICON_VOLUME_2 u8"\uE0F1"   // volume-2
#define ICON_VOLUME_X u8"\uE0F2"   // volume-x
#define ICON_VOLUME u8"\uE0F3"   // volume
#define ICON_WATCH u8"\uE0F4"   // watch
#define ICON_WIFI_OFF u8"\uE0F5"   // wifi-off
#define ICON_WIFI u8"\uE0F6"   // wifi
#define ICON_WIND u8"\uE0F7"   // wind
#define ICON_X_CIRCLE u8"\uE0F8"   // x-circle
#define ICON_X_SQUARE u8"\uE0F9"   // x-square
#define ICON_X u8"\uE0FA"   // x
#define ICON_ZAP_OFF u8"\uE0FB"   // zap-off
#define ICON_ZAP u8"\uE0FC"   // zap
#define ICON_ZOOM_IN u8"\uE0FD"   // zoom-in
#define ICON_ZOOM_OUT u8"\uE0FE"   // zoom-out

// End of icon definitions
